name: Deploy to GitHub Pages

on:
  push:
    branches: ['main', 'master']
  workflow_dispatch:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install dependencies
        run: |
          npm install 
          python -m pip install --upgrade pip
          pip install pandas

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run convert-features.py
        run: python ./convert-features.py
        working-directory: data-conversion

      - name: Run convert-metadata.py
        run: python ./convert-metadata.py
        working-directory: data-conversion

      - name: Move files to /static
        run: |
          mkdir -p static
          mv -f data-conversion/features.geojson static/features.geojson
          mv -f data-conversion/metadata.json static/metadata.json

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          NODE_OPTIONS: '--max_old_space_size=9000'
          PUBLIC_MAPTILER_API_KEY: ${{ secrets.PUBLIC_MAPTILER_API_KEY }}
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
