name: Process Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert_and_move:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run convert-features.py
        run: python data-conversion/convert-features.py

      - name: Run convert-metadata.py
        run: python data-conversion/convert-metadata.py

      - name: Move files to /static
        run: |
          mkdir -p static
          mv -f data-conversion/features.geojson static/features.geojson
          mv -f data-conversion/metadata.json static/metadata.json

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update features.geojson and metadata.json"
          add: 'static/*,data-conversion/*'
