name: Process Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert_and_move:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run convert-features.py
        run: python ./convert-features.py
        working-directory: data-conversion

      - name: Run convert-metadata.py
        run: python ./convert-metadata.py
        working-directory: data-conversion

      - name: Move files to /static
        run: |
          mkdir -p static
          mv -f data-conversion/features.geojson static/features.geojson
          mv -f data-conversion/metadata.json static/metadata.json
